### ISSUE TITLE
Could not load type 'StructureMap.Configuration.DSL.Registry' 

### ISSUE THREAD

**Issue by Cortlendt** [NancyFx/Nancy.Bootstrappers.StructureMap#38]
Structuremap 4.1.0.318
Nancy 1.4.3

using (var host = new NancyHost(uri, new Bootstrapper(), hostConfigs))

Could not load type 'StructureMap.Configuration.DSL.Registry' from assembly 'StructureMap, Version=4.0.1.318, Culture=neutral, PublicKeyToken=null'.

   at Nancy.Bootstrappers.StructureMap.StructureMapNancyBootstrapper.<RegisterBootstrapperTypes>b__0(ConfigurationExpression registry)
   at StructureMap.PipelineGraph.Configure(Action`1 configure) in C:\BuildAgent\work\a395dbde6b793293\src\StructureMap.Shared\PipelineGraph.cs:line 170
   at StructureMap.Container.Configure(Action`1 configure) in C:\BuildAgent\work\a395dbde6b793293\src\StructureMap.Shared\Container.cs:line 806
   at Nancy.Bootstrappers.StructureMap.StructureMapNancyBootstrapper.RegisterBootstrapperTypes(IContainer applicationContainer)
   at Nancy.Bootstrapper.NancyBootstrapperBase`1.Initialise()
   at Nancy.Hosting.Self.NancyHost..ctor(INancyBootstrapper bootstrapper, HostConfiguration configuration, Uri[] baseUris)
   at Nancy.Hosting.Self.NancyHost..ctor(Uri baseUri, INancyBootstrapper bootstrapper, HostConfiguration configuration)
   at Api.Push.ManagementInterface.Nancy.EntryPoint.Main(String[] args) in C:\Projects\api-push\src\Api.Push\ManagementInterface\Api.Push.ManagementInterface.Nancy\EntryPoint.cs:line 19
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)

**Comment by khellang** [comment]
Huh. Is this a breaking change in v4? @jeremydmiller? This bootstrapper hasn't been updated to use v4, so if there are breaking changes, it won't work.

**Comment by jeremydmiller** [comment]
@khellang `Registry` moved to the root "StructureMap" namespace. Sorry about the break, but that's bugged me for years and 4.0 was the opportunity to finally fix that.

**Comment by jvandertil** [comment]
I can create a PR to upgrade the bootstrapper to v4 which should keep people going for now. Are there any big changes with to the bootstrapper coming with Nancy 2.0?

**Comment by khellang** [comment]
I'll see if we can get a new version pushed this week :smile:

**Comment by jvandertil** [comment]
@khellang any news on the new version? :)

**Comment by aaron-hammond** [comment]
@jvandertil This change got pushed today. https://www.nuget.org/packages/Nancy.BootStrappers.StructureMap/ 
Version 1.4.3
